GET http://localhost:3000/books

###
GET http://localhost:3000/books/1

###
POST  http://localhost:3000/books
Content-Type: application/json

{
    "title":"Dodo",
    "type":"borz",
    "price":9
}

###
DELETE http://localhost:3000/books/1

###
Patch http://localhost:3000/books/1
Content-Type: application/json

{
    "price": 900
}