GET http://localhost:3000/books

###
GET http://localhost:3000/books/1

###
POST  http://localhost:3000/books

{
    "title":"Dodo",
    "type":"borz",
    "price":9
}

###
DELETE http://localhost:3000/books/1
###
Patch http://localhost:3000/books/c0a67dcb-3aee-4ba1-8fca-ca4c5ff19de6
Content-Type: application/json
{
    "type": "Pevná nešitá väzba"
}